/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gradesystem;

import javax.swing.JButton;

/**
 *
 * @author USER
 */
public class MENU extends javax.swing.JFrame {
 private JButton menuButton;
    /**
     * Creates new form MENU
     */
    public MENU() {
        initComponents();
         menuButton = new JButton("Menu");
        // Initialize your button and add it to the frame
        add(menuButton);
    }
    public JButton getMenuButton() {
        return menuButton;
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        MENU = new javax.swing.JToggleButton();
        PRELIM = new javax.swing.JToggleButton();
        AVERAGE = new javax.swing.JToggleButton();
        FINAL1 = new javax.swing.JToggleButton();
        MIDTERM1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 740));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        jLabel5.setText("≡");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 50, 40));

        MENU.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        MENU.setSelected(true);
        MENU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MENUActionPerformed(evt);
            }
        });
        jPanel1.add(MENU, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        PRELIM.setBackground(new java.awt.Color(204, 204, 204));
        PRELIM.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        PRELIM.setText("PRELIM GRADE");
        PRELIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRELIMActionPerformed(evt);
            }
        });
        jPanel1.add(PRELIM, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 400, 80));

        AVERAGE.setBackground(new java.awt.Color(204, 204, 204));
        AVERAGE.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        AVERAGE.setText("AVERAGE GRADES");
        AVERAGE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AVERAGEActionPerformed(evt);
            }
        });
        jPanel1.add(AVERAGE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 400, 80));

        FINAL1.setBackground(new java.awt.Color(204, 204, 204));
        FINAL1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        FINAL1.setText(" FINAL GRADE");
        FINAL1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FINAL1ActionPerformed(evt);
            }
        });
        jPanel1.add(FINAL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 400, 80));

        MIDTERM1.setBackground(new java.awt.Color(204, 204, 204));
        MIDTERM1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        MIDTERM1.setText("MIDTERM GRADE");
        MIDTERM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIDTERM1ActionPerformed(evt);
            }
        });
        jPanel1.add(MIDTERM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 400, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
     setVisible(false);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void MENUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MENUActionPerformed
    setVisible(false);
    }//GEN-LAST:event_MENUActionPerformed
    

    private GradeManagementSystem1 frame1;
    private GradeManagementSystem frame2;
    private GradeManagementSystem2 frame3;
    private GradeManagementSystem3 frame4;
    private void PRELIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRELIMActionPerformed
    if (frame1 == null) {
        frame1 = new GradeManagementSystem1();  // Create instance of frame1
        frame1.setVisible(true);  // Show frame1
    } else {
        frame1.setVisible(true);  // If it's already created, just make it visible
    }

    // Dispose of other frames if they are created
    if (frame2 != null) {
        frame2.dispose();
        frame2 = null;
    }
    if (frame3 != null) {
        frame3.dispose();
        frame3 = null;
    }
    if (frame4 != null) {
        frame4.dispose();
        frame4 = null;
    }
    }//GEN-LAST:event_PRELIMActionPerformed
    
    private void MIDTERM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIDTERM1ActionPerformed
    if (frame3 == null) {
        frame3 = new GradeManagementSystem2();  // Create instance of frame3
        frame3.setVisible(true);  // Show frame3
    } else {
        frame3.setVisible(true);  // If it's already created, just make it visible
    }

    // Dispose of other frames if they are created
    if (frame1 != null) {
        frame1.dispose();
        frame1 = null;
    }
    if (frame2 != null) {
        frame2.dispose();
        frame2 = null;
    }
    if (frame4 != null) {
        frame4.dispose();
        frame4 = null;
    }
    }//GEN-LAST:event_MIDTERM1ActionPerformed

    private void FINAL1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FINAL1ActionPerformed
      if (frame4 == null) {
        frame4 = new GradeManagementSystem3();  // Create instance of frame4
        frame4.setVisible(true);  // Show frame4
    } else {
        frame4.setVisible(true);  // If it's already created, just make it visible
    }

    // Dispose of other frames if they are created
    if (frame1 != null) {
        frame1.dispose();
        frame1 = null;
    }
    if (frame2 != null) {
        frame2.dispose();
        frame2 = null;
    }
    if (frame3 != null) {
        frame3.dispose();
        frame3 = null;
    }
    }//GEN-LAST:event_FINAL1ActionPerformed

    private void AVERAGEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AVERAGEActionPerformed
    if (frame2 == null) {
        frame2 = new GradeManagementSystem();  // Create instance of frame2
        frame2.setVisible(true);  // Show frame2
    } else {
        frame2.setVisible(true);  // If it's already created, just make it visible
    }

    // Dispose of other frames if they are created
    if (frame1 != null) {
        frame1.dispose();
        frame1 = null;
    }
    if (frame3 != null) {
        frame3.dispose();
        frame3 = null;
    }
    if (frame4 != null) {
        frame4.dispose();
        frame4 = null;
    }
    }//GEN-LAST:event_AVERAGEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MENU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton AVERAGE;
    private javax.swing.JToggleButton FINAL1;
    private javax.swing.JToggleButton MENU;
    private javax.swing.JToggleButton MIDTERM1;
    private javax.swing.JToggleButton PRELIM;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
